server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Sirve la app; si la ruta no existe, devuelve index.html (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }


